name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'

    - name: Initialize Go module
      run: go mod init create-html-project
      working-directory: ./src

    - name: Build
      run: go build -o ./bin/main.exe ./src

    - name: Test
      run: go test -v ./src
